spring.application.name=API-learning
spring.datasource.url=jdbc:mysql://localhost:3306/movie_db
spring.datasource.password=2006
spring.datasource.username=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true;

